parameters:
    my_user_provider.class: aos\UserBundle\OAuth\FOSUBUserProvider

services:
    my_user_provider:
        class: "%my_user_provider.class%"
        arguments: [@fos_user.user_manager,{facebook: facebook_id,github: github_id,google: google_id,linkedin: linkedin_id}]